from fastapi import APIRouter, Depends
from sqlmodel import Session, select
from app.api.dependencies import get_db_session
from app.models.identity import IdentityProfile, KnowledgeBase, get_srvdb_instance

router = APIRouter()

@router.get("")
# @router.get("/")
def get_identities(session: Session = Depends(get_db_session)):
    """Retrieve the active Identity Profile and its SrvDB KnowledgeBase pillars."""
    profile = session.exec(select(IdentityProfile)).first()
    if not profile:
        return {"profile": None, "knowledge_base": []}
        
    services = session.exec(
        select(KnowledgeBase).where(KnowledgeBase.identity_id == profile.id)
    ).all()
    
    return {
        "profile": profile.model_dump(),
        "knowledge_base": [s.model_dump() for s in services]
    }

@router.post("")
# @router.post("/")
def save_identity(data: dict, session: Session = Depends(get_db_session)):
    """
    Saves the user's white-labeled IdentityProfile and persists KnowledgeBase 
    entries into the local SrvDB vector store.
    """
    profile_data = data.get("profile", {})
    services_data = data.get("knowledge_base", [])
    
    # 1. Update or Create Identity
    profile = session.exec(select(IdentityProfile)).first()
    if not profile:
        profile = IdentityProfile(**profile_data)
        session.add(profile)
        session.commit()
    else:
        for k, v in profile_data.items():
            if hasattr(profile, k):
                setattr(profile, k, v)
        session.add(profile)
        session.commit()
        
    session.refresh(profile)
    
    # 2. Sync Knowledge Base to SQLite
    existing_services = session.exec(
        select(KnowledgeBase).where(KnowledgeBase.identity_id == profile.id)
    ).all()
    
    for s in existing_services:
        session.delete(s)
    session.commit()
    
    new_services = []
    for s_data in services_data:
        kb_entry = KnowledgeBase(**s_data, identity_id=profile.id)
        session.add(kb_entry)
        new_services.append(kb_entry)
        
    session.commit()
    
    # 3. Embed into SrvDB Vector Store
    if new_services:
        try:
            db = get_srvdb_instance()
            
            # Using mock 384 embeddings for fast local setup (matching our dimension in identity.py)
            # In a production AI agent pipeline, these would be generated by a live embedding model.
            import numpy as np
            
            ids = [f"kb_{s.id}" for s in new_services]
            metadatas = [s.model_dump_json() for s in new_services]
            mock_embeddings = np.random.randn(len(new_services), 384).astype(np.float32).tolist()
            
            db.add(ids=ids, embeddings=mock_embeddings, metadatas=metadatas)
            db.persist()
            
            # Mark as embedded
            for s in new_services:
                s.is_embedded = True
                session.add(s)
            session.commit()
        except Exception as e:
            # SrvDB might fail if numpy is missing, we gracefully catch to not crash UI saves
            print(f"Warning: SrvDB Embedding skipped: {e}")
    
    return {"status": "success", "profile_id": profile.id}
